vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        agencies:
            uri_prefix: /images/agencies
            upload_destination: '%kernel.project_dir%/public/images/agencies'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        vehicles:
            uri_prefix: /images/vehicles
            upload_destination: '%kernel.project_dir%/public/images/vehicles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true